#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

#define RP2040_FLASH_GENERIC_03H



#define AZOTEQ_IQS5XX_TPS65
#define AZOTEQ_IQS5XX_PRESS_AND_HOLD_ENABLE TRUE
#define AZOTEQ_IQS5XX_ROTATION_90
//#define POINTING_DEVICE_MOTION_PIN GP6

#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP4
#define I2C1_SCL_PIN GP5
